remote_theme: pmarsceill/just-the-docs
title: Simon Erlic's Blog'
ooter_content: "Copyright &copy; 2017-2019 Simon Erlic. Using "just the docs" by pmarsceill</a>
search_enabled: true
baseurl: "/blog"
url: "simonerlic.github.io/simon.erlic.ca"
ga_tracking: UA-151752052-1
